// backend/email/pdf_generator.ts

import PDFDocument from 'pdfkit';
import axios from 'axios';

/**
 * PDF Dossier Generator — PRD Section 5
 *
 * Generates a 5-page classified-style intelligence report from a consolidated dossier.
 *
 * @param dossier - Consolidated email or telephone scan dossier
 * @returns PDF buffer
 */
export async function generateDossierPDF(dossier: any): Promise<Buffer> {
  let avatarBuffer: Buffer | null = null;
  const isPhone = !!dossier.phone;

  if (isPhone) {
    try {
      const cleanPhone = dossier.phone.trim().replace(/\s+/g, '');
      const rawDigits = cleanPhone.replace('+', '');
      const avatarUrl = `https://i.pravatar.cc/150?u=${rawDigits}`;
      const imgRes = await axios.get(avatarUrl, {
        responseType: 'arraybuffer',
        timeout: 2500
      });
      if (imgRes.status === 200) {
        avatarBuffer = Buffer.from(imgRes.data);
      }
    } catch {
      // Safe fallback — ignore timeout/error
    }
  } else if (dossier.gravatar && dossier.gravatar.avatarUrl) {
    try {
      const imgRes = await axios.get(dossier.gravatar.avatarUrl, {
        responseType: 'arraybuffer',
        timeout: 2500
      });
      if (imgRes.status === 200) {
        avatarBuffer = Buffer.from(imgRes.data);
      }
    } catch {
      // Safe fallback
    }
  }

  return new Promise<Buffer>((resolve, reject) => {
    const targetTitle = isPhone ? maskPhone(dossier.phone) : maskEmail(dossier.email);

    const doc = new PDFDocument({
      size: 'A4',
      margins: { top: 50, bottom: 50, left: 60, right: 60 },
      info: {
        Title: 'OSINT Intelligence Dossier',
        Author: 'Antigravity OSINT Suite',
        Subject: `Digital Footprint Analysis: ${targetTitle}`,
      },
    });

    const chunks: Buffer[] = [];
    doc.on('data', (chunk: any) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    if (isPhone) {
      // ─── PAGE 1: COVER ───
      renderPhoneCover(doc, dossier);

      // ─── PAGE 2: SUBJECT PROFILE ───
      doc.addPage();
      renderPhoneSubjectProfile(doc, dossier, avatarBuffer);

      // ─── PAGE 3: OTT & SOCIAL ACCOUNTS ───
      doc.addPage();
      renderPhoneSocialAccounts(doc, dossier);
    } else {
      // ─── PAGE 1: COVER ───
      renderCover(doc, dossier);

      // ─── PAGE 2: SUBJECT PROFILE ───
      doc.addPage();
      renderSubjectProfile(doc, dossier, avatarBuffer);

      // ─── PAGE 3: PLATFORM FINDINGS ───
      doc.addPage();
      renderPlatformFindings(doc, dossier);

      // ─── PAGE 4: BREACH DETAILS ───
      doc.addPage();
      renderBreachDetails(doc, dossier);

      // ─── PAGE 5: APPENDIX ───
      doc.addPage();
      renderAppendix(doc, dossier);
    }

    doc.end();
  });
}

// ─── Page Renderers ───

function renderCover(doc: typeof PDFDocument | any, dossier: any) {
  doc.moveDown(6);

  // Classified banner
  doc.fontSize(14).font('Helvetica-Bold').fillColor('#cc0000')
    .text('████ TOP SECRET ████', { align: 'center' });
  doc.moveDown(0.5);

  doc.fontSize(22).font('Helvetica-Bold').fillColor('#1a1a2e')
    .text('CLASSIFIED INVESTIGATION', { align: 'center' });
  doc.moveDown(0.3);

  doc.fontSize(16).fillColor('#333')
    .text('DIGITAL FOOTPRINT ANALYSIS', { align: 'center' });
  doc.moveDown(2);

  doc.fontSize(12).font('Helvetica').fillColor('#555')
    .text(`Target: ${maskEmail(dossier.email)}`, { align: 'center' });
  doc.moveDown(0.5);
  doc.text(`Date: ${new Date().toISOString().replace('T', ' ').slice(0, 19)} UTC`, { align: 'center' });
  doc.moveDown(0.5);
  doc.text(`Analysis Duration: ${dossier.timeTakenMs}ms`, { align: 'center' });

  doc.moveDown(4);

  // Footer line
  doc.fontSize(8).fillColor('#999')
    .text('Generated by Antigravity OSINT Intelligence Suite', { align: 'center' });
  doc.text('For authorized use only. Handle according to classification level.', { align: 'center' });
}

function renderSubjectProfile(doc: typeof PDFDocument | any, dossier: any, avatarBuffer: Buffer | null = null) {
  doc.fontSize(16).font('Helvetica-Bold').fillColor('#1a1a2e')
    .text('SUBJECT PROFILE', { align: 'left' });
  doc.moveDown(0.5);
  drawHR(doc);
  doc.moveDown(1);

  const identity = dossier.identity || {};
  const gravatar = dossier.gravatar || {};

  // Draw Avatar Box on top right dynamically if possible
  const currentY = doc.y;
  if (avatarBuffer) {
    try {
      // Rounded border rect
      doc.lineWidth(2).strokeColor('#0066cc').rect(438, currentY - 2, 94, 94).stroke();
      doc.image(avatarBuffer, 440, currentY, { width: 90, height: 90 });
    } catch {
      // Graceful fallback to placeholder box
      doc.lineWidth(1).strokeColor('#888').dash(3, { space: 3 }).rect(440, currentY, 90, 90).stroke();
      doc.fontSize(16).fillColor('#888').text('👤', 472, currentY + 35);
      doc.undash();
    }
  } else if (gravatar.hasGravatar) {
    doc.lineWidth(1).strokeColor('#888').dash(3, { space: 3 }).rect(440, currentY, 90, 90).stroke();
    doc.fontSize(22).fillColor('#888').text('👤', 470, currentY + 30);
    doc.undash();
  }

  // Restore doc text position to align nicely with avatar
  doc.y = currentY;

  const fields = [
    ['Email', dossier.email],
    ['Real Name', identity.realName || 'Not Resolved'],
    ['Employer', identity.employer || 'Unknown'],
    ['Position', identity.position || 'Unknown'],
    ['Confidence', identity.confidence || 'LOW'],
    ['Gravatar', gravatar.hasGravatar ? 'Found' : 'Not Found'],
    ['Breach Count', `${(dossier.breaches || []).length} breach(es)`],
    ['Sources', (identity.sources || []).join(', ') || 'None'],
  ];

  doc.fontSize(11).font('Helvetica');
  for (const [label, value] of fields) {
    doc.fillColor('#555').text(`${label}:`, { continued: true });
    doc.fillColor('#1a1a2e').text(`  ${value}`, { width: 350 });
    doc.moveDown(0.35);
  }

  if (gravatar.avatarUrl) {
    doc.moveDown(1.5);
    doc.fontSize(9).fillColor('#888').text(`Avatar Source URL: ${gravatar.avatarUrl}`);
  }
}

function renderPlatformFindings(doc: typeof PDFDocument | any, dossier: any) {
  doc.fontSize(16).font('Helvetica-Bold').fillColor('#1a1a2e')
    .text('PLATFORM FINDINGS', { align: 'left' });
  doc.moveDown(0.5);
  drawHR(doc);
  doc.moveDown(1);

  const usernames = dossier.usernames || {};

  doc.fontSize(11).font('Helvetica').fillColor('#333');
  doc.text(`Primary Username: ${usernames.primary || 'N/A'}`);
  doc.moveDown(0.3);
  doc.text(`Variants Searched: ${(usernames.variants || []).join(', ') || 'None'}`);
  doc.moveDown(1);

  // Platform scan results table (if platformResults exist on dossier)
  if (dossier.platformResults && dossier.platformResults.length > 0) {
    doc.fontSize(10).font('Helvetica-Bold');
    doc.text('Platform', 60, doc.y, { width: 120 });
    doc.text('Status', 180, doc.y, { width: 80 });
    doc.text('URL', 260, doc.y, { width: 250 });
    doc.moveDown(0.5);
    drawHR(doc);

    doc.font('Helvetica').fontSize(9);
    for (const result of dossier.platformResults) {
      if (doc.y > 750) {
        doc.addPage();
      }
      const statusColor = result.status === 'FOUND' ? '#00aa55' : '#999';
      doc.fillColor('#333').text(result.platform, 60, doc.y, { width: 120 });
      doc.fillColor(statusColor).text(result.status, 180, doc.y, { width: 80 });
      doc.fillColor('#555').text(result.url || '', 260, doc.y, { width: 250 });
      doc.moveDown(0.3);
    }
  } else {
    doc.fontSize(10).fillColor('#888')
      .text('No platform scan results included in this dossier.');
  }
}

function renderBreachDetails(doc: typeof PDFDocument | any, dossier: any) {
  doc.fontSize(16).font('Helvetica-Bold').fillColor('#1a1a2e')
    .text('BREACH DETAILS', { align: 'left' });
  doc.moveDown(0.5);
  drawHR(doc);
  doc.moveDown(1);

  const breaches = dossier.breaches || [];

  if (breaches.length === 0) {
    doc.fontSize(11).font('Helvetica').fillColor('#888')
      .text('No known breaches found for this email address.');
    return;
  }

  for (const breach of breaches) {
    if (doc.y > 700) {
      doc.addPage();
    }

    doc.fontSize(12).font('Helvetica-Bold').fillColor('#cc0000')
      .text(breach.name || 'Unknown Breach');
    doc.fontSize(10).font('Helvetica').fillColor('#555');
    doc.text(`Domain: ${breach.domain || 'N/A'} | Date: ${breach.breachDate || 'Unknown'} | Records: ${formatNumber(breach.pwnCount)}`);
    doc.moveDown(0.3);
    doc.text(`Compromised Data: ${(breach.compromisedData || []).join(', ')}`);
    doc.moveDown(0.3);

    if (breach.description) {
      // Strip HTML tags from description
      const cleanDesc = breach.description.replace(/<[^>]*>/g, '');
      doc.fontSize(9).fillColor('#666').text(cleanDesc, { width: 460 });
    }

    doc.moveDown(1);
  }
}

function renderAppendix(doc: typeof PDFDocument | any, dossier: any) {
  doc.fontSize(16).font('Helvetica-Bold').fillColor('#1a1a2e')
    .text('APPENDIX', { align: 'left' });
  doc.moveDown(0.5);
  drawHR(doc);
  doc.moveDown(1);

  const usernames = dossier.usernames || {};
  const perms = dossier.permutations || {};

  doc.fontSize(11).font('Helvetica-Bold').fillColor('#333')
    .text('Usernames Checked:');
  doc.fontSize(10).font('Helvetica').fillColor('#555');
  doc.text(`Primary: ${usernames.primary || 'N/A'}`);
  doc.text(`Variants: ${(usernames.variants || []).join(', ') || 'None'}`);
  doc.moveDown(1);

  doc.fontSize(11).font('Helvetica-Bold').fillColor('#333')
    .text('Email Permutations Tested:');
  doc.fontSize(10).font('Helvetica').fillColor('#555');
  doc.text(`Work: ${(perms.workEmails || []).join(', ') || 'None'}`);
  doc.text(`Personal: ${(perms.personalEmails || []).join(', ') || 'None'}`);
  doc.moveDown(1);

  doc.fontSize(11).font('Helvetica-Bold').fillColor('#333')
    .text('Scan Methodology:');
  doc.fontSize(9).font('Helvetica').fillColor('#666');
  doc.text('• Email syntax validated against RFC 5322');
  doc.text('• Domain MX records checked via DNS lookup');
  doc.text('• Breach data from HaveIBeenPwned API (or mock database for lab)');
  doc.text('• Gravatar avatar and profile via MD5 hash lookup');
  doc.text('• Identity resolved via waterfall: Hunter.io → Gravatar → Email pattern');
  doc.text('• Username variants generated and cross-checked across 40+ platforms');
  doc.text('• Email permutations generated from resolved identity and username');
  doc.moveDown(2);

  doc.fontSize(8).fillColor('#aaa')
    .text('This document was auto-generated. Data sourced from publicly available information only.', { align: 'center' });
  doc.text(`Generated: ${new Date().toISOString()}`, { align: 'center' });
}

// ─── Telephone Renderers ───

function renderPhoneCover(doc: typeof PDFDocument | any, dossier: any) {
  doc.moveDown(6);
  // Classified banner
  doc.fontSize(14).font('Helvetica-Bold').fillColor('#cc0000')
    .text('████ TOP SECRET ████', { align: 'center' });
  doc.moveDown(0.5);

  doc.fontSize(22).font('Helvetica-Bold').fillColor('#1a1a2e')
    .text('CLASSIFIED INVESTIGATION', { align: 'center' });
  doc.moveDown(0.3);

  doc.fontSize(16).fillColor('#333')
    .text('TELEPHONE DIGITAL FOOTPRINT', { align: 'center' });
  doc.moveDown(2);

  doc.fontSize(12).font('Helvetica').fillColor('#555')
    .text(`Target: ${maskPhone(dossier.phone)}`, { align: 'center' });
  doc.moveDown(0.5);
  doc.text(`Date: ${new Date().toISOString().replace('T', ' ').slice(0, 19)} UTC`, { align: 'center' });
  doc.moveDown(0.5);
  doc.text(`Analysis Duration: ${dossier.timeTakenMs || 0}ms`, { align: 'center' });

  doc.moveDown(4);

  // Footer line
  doc.fontSize(8).fillColor('#999')
    .text('Generated by Antigravity OSINT Intelligence Suite', { align: 'center' });
  doc.text('For authorized use only. Handle according to classification level.', { align: 'center' });
}

function renderPhoneSubjectProfile(doc: typeof PDFDocument | any, dossier: any, avatarBuffer: Buffer | null = null) {
  doc.fontSize(16).font('Helvetica-Bold').fillColor('#1a1a2e')
    .text('TELEPHONE SUBJECT PROFILE', { align: 'left' });
  doc.moveDown(0.5);
  drawHR(doc);
  doc.moveDown(1);

  const val = dossier.validation || {};
  const caller = dossier.callerId || {};
  const people = dossier.peopleSearch || {};

  // Draw Avatar Box on top right dynamically if possible
  const currentY = doc.y;
  if (avatarBuffer) {
    try {
      // Rounded border rect
      doc.lineWidth(2).strokeColor('#0066cc').rect(438, currentY - 2, 94, 94).stroke();
      doc.image(avatarBuffer, 440, currentY, { width: 90, height: 90 });
    } catch {
      // Graceful fallback to placeholder box
      doc.lineWidth(1).strokeColor('#888').dash(3, { space: 3 }).rect(440, currentY, 90, 90).stroke();
      doc.fontSize(16).fillColor('#888').text('👤', 472, currentY + 35);
      doc.undash();
    }
  } else {
    doc.lineWidth(1).strokeColor('#888').dash(3, { space: 3 }).rect(440, currentY, 90, 90).stroke();
    doc.fontSize(22).fillColor('#888').text('👤', 470, currentY + 30);
    doc.undash();
  }

  // Restore doc text position to align nicely with avatar
  doc.y = currentY;

  const fields = [
    ['Normalized Target', val.formatted || dossier.phone],
    ['Carrier Name', val.carrier || 'Unknown'],
    ['Country Code', val.countryCode || 'N/A'],
    ['Caller Name', caller.realName || 'Not Resolved'],
    ['Physical Location', caller.location || 'Unknown'],
    ['Confidence Level', 'HIGH'],
    ['Resolved Employer', people.business || 'Unknown'],
    ['Physical Address', people.realAddress || 'Not Found'],
    ['Caller Sources', (caller.sources || []).join(', ') || 'None'],
  ];

  doc.fontSize(11).font('Helvetica');
  for (const [label, value] of fields) {
    doc.fillColor('#555').text(`${label}:`, { continued: true });
    doc.fillColor('#1a1a2e').text(`  ${value}`, { width: 350 });
    doc.moveDown(0.35);
  }

  doc.moveDown(2);

  // Associates & Relatives Section
  doc.fontSize(13).font('Helvetica-Bold').fillColor('#1a1a2e')
    .text('ASSOCIATES & RELATIVES (FOOTPRINT MAP)', { align: 'left' });
  doc.moveDown(0.4);
  drawHR(doc);
  doc.moveDown(0.8);

  const relatives = people.relatives || [];
  if (relatives.length > 0) {
    doc.fontSize(10).font('Helvetica').fillColor('#333');
    for (const rel of relatives) {
      doc.text(`  • ${rel}`);
      doc.moveDown(0.4);
    }
  } else {
    doc.fontSize(10).font('Helvetica-Oblique').fillColor('#888')
      .text('  No known relatives or associates identified.');
  }
}

function renderPhoneSocialAccounts(doc: typeof PDFDocument | any, dossier: any) {
  doc.fontSize(16).font('Helvetica-Bold').fillColor('#1a1a2e')
    .text('OTT SOCIAL DISCOVERY & METHODOLOGY', { align: 'left' });
  doc.moveDown(0.5);
  drawHR(doc);
  doc.moveDown(1);

  const social = dossier.socialSync || {};
  const ottProfiles = social.ottProfiles || [];
  const fb = social.facebook || {};

  doc.fontSize(12).font('Helvetica-Bold').fillColor('#1a1a2e').text('Simulated OTT App Profiles:');
  doc.moveDown(0.5);

  if (ottProfiles.length > 0) {
    for (const p of ottProfiles) {
      doc.fontSize(10).font('Helvetica-Bold').fillColor('#0066cc').text(`[✓] ${p.app}`);
      doc.fontSize(9).font('Helvetica').fillColor('#333');
      doc.text(`   Display Name: ${p.displayName}`);
      doc.text(`   Username: ${p.username}`);
      doc.text(`   Avatar Source: ${p.avatarUrl}`);
      doc.moveDown(0.4);
    }
  } else {
    doc.fontSize(10).font('Helvetica').fillColor('#999').text('No simulated OTT accounts resolved.');
    doc.moveDown(0.5);
  }

  doc.moveDown(1);

  if (fb.profileUrl) {
    doc.fontSize(12).font('Helvetica-Bold').fillColor('#1a1a2e').text('Facebook Discovery Matches:');
    doc.moveDown(0.3);
    doc.fontSize(10).font('Helvetica').fillColor('#333');
    doc.text(`   Candidate Name: ${fb.candidateName}`);
    doc.text(`   Profile URL: ${fb.profileUrl}`);
    doc.text(`   Page Entity: ${fb.pageName}`);
    doc.moveDown(1.5);
  }

  doc.fontSize(12).font('Helvetica-Bold').fillColor('#1a1a2e').text('Scan Methodology:');
  doc.fontSize(9).font('Helvetica').fillColor('#666');
  doc.text('• E.164 target phone normalization and auto-correction of double prefixes');
  doc.text('• VN carrier identification based on routing registries');
  doc.text('• Reverse lookup Caller ID lookup with Twilio API');
  doc.text('• Unified deterministic profile mocking ensuring cross-lane consistency');
  doc.text('• Simulated OTT profile checking (WhatsApp, Telegram, Zalo)');
  doc.moveDown(2);

  doc.fontSize(8).fillColor('#aaa')
    .text('This document was auto-generated. Data sourced from publicly available information only.', { align: 'center' });
  doc.text(`Generated: ${new Date().toISOString()}`, { align: 'center' });
}

// ─── Utilities ───

function drawHR(doc: typeof PDFDocument | any) {
  const y = doc.y;
  doc.moveTo(60, y).lineTo(535, y).strokeColor('#ddd').lineWidth(1).stroke();
  doc.moveDown(0.3);
}

export function maskEmail(email: string): string {
  if (!email || !email.includes('@')) return email || 'N/A';
  const [local, domain] = email.split('@');
  if (local.length <= 3) return `${local[0]}***@${domain}`;
  return `${local.slice(0, 3)}***@${domain}`;
}

export function maskPhone(phone: string): string {
  if (!phone) return 'N/A';
  const clean = phone.trim().replace(/\s+/g, '').replace(/[\(\)\-]/g, '');

  let countryCode = '';
  let local = clean;

  if (clean.startsWith('+')) {
    // Dynamic matching of popular country code lengths: 1, 2, or 3 digits
    if (clean.startsWith('+84') || clean.startsWith('+44') || clean.startsWith('+61') || clean.startsWith('+81')) {
      countryCode = clean.slice(0, 3);
      local = clean.slice(3);
    } else if (clean.startsWith('+1')) {
      countryCode = clean.slice(0, 2);
      local = clean.slice(2);
    } else {
      const match = clean.match(/^\+(\d{1,3})/);
      if (match) {
        countryCode = match[0];
        local = clean.slice(countryCode.length);
      }
    }
  }

  if (local.length >= 6) {
    const prefixLen = Math.min(3, Math.floor(local.length / 3));
    const suffixLen = Math.min(3, Math.floor(local.length / 3));
    const maskLen = local.length - prefixLen - suffixLen;
    const maskStr = '*'.repeat(maskLen);
    return `${countryCode} ${local.slice(0, prefixLen)} ${maskStr} ${local.slice(-suffixLen)}`.trim();
  }

  if (clean.length > 6) {
    return `${clean.slice(0, 3)} *** ${clean.slice(-3)}`;
  }
  return clean;
}

function formatNumber(num: number): string {
  if (!num) return '0';
  return num.toLocaleString('en-US');
}
